### ISSUE TITLE
Python version pinning

### ISSUE THREAD

**Issue by SultanOrazbayev** [coiled/coiled-runtime#121]
If I installed environment with the environment below (python is not pinned)

```yaml
name: test_coiled
channels:
- conda-forge
dependencies:
- python
- coiled-runtime=0.0.3
```

Then python 3.10 is installed on my machine (MacOS). However, later coiled asks for python 3.9 version.

Steps to reproduce:
- save the above yaml as environment.yml
```shell
conda env create -f environment.yml
conda activate test_coiled
python --version
```

The above prints `3.10.4`.

**Comment by SultanOrazbayev** [comment]
To elaborate on the coiled error message:

```python
from coiled.v2 import Cluster
cluster = Cluster(n_workers=1, account="sultanorazbayev")
```
I got the error ServerError: Software environment `coiled/default-py310` not found

Specifying 3.9 using this works, but will give inconsistent python versions on client/workers:

```python
cluster = Cluster(n_workers=1, account="sultanorazbayev", software="coiled/default-py39")
```

**Comment by ncclementi** [comment]
@SultanOrazbayev Thank you for reporting this!. 

@jrbourbeau Should we pin the python version to be < 3.10 in the recipe? and probably patch the release in the feedstock?

**Comment by ncclementi** [comment]
@SultanOrazbayev we just fixed this in the feedstock, not sure how long it takes to kick in, but probably in a couple of hours, this shouldn't be a problem anymore.

**Comment by SultanOrazbayev** [comment]
Interesting, I just reproduced the same issue (python installed is still 3.10.4)... (it's not a big one, though, just wanted to let you know).

**Comment by ncclementi** [comment]
@SultanOrazbayev 
Mmh I'm not able to reproduce what you say. I just upgrade my python to 3.10.4 on the base environment, then create a new environment installing the `coiled-runtime` and it installed python 3.9.12 

My guess is you might have a cached version of the coiled-runtime package which is probably causing this.

**Comment by SultanOrazbayev** [comment]
That's very odd, I just tried it on another computer (Ubuntu) where I did not have coiled previously and still able to reproduce. I am using `conda-forge` channel, could that be an issue?

**Comment by SultanOrazbayev** [comment]
I tried adding `coiled` as a higher priority channel, but the original issue is still reproduced.

However, I just wanted to report it, it's not a blocking issue for me.

**Comment by ncclementi** [comment]
@SultanOrazbayev Thank you for reporting it.  You shouldn't use the coiled channel, as that is an older version of the runtime and we are not maintaining it, except for nightly builds. 

conda-forge is the way to go, I'm curious why it's not working for you, @jrbourbeau do you know what could be happening here?

**Comment by jrbourbeau** [comment]
> Mmh I'm not able to reproduce what you say ... create a new environment installing the coiled-runtime and it installed python 3.9.12

Same here. I tried with both `conda` and `mamba` and with both `python=3.9.12` was installed. 

@SultanOrazbayev can you paste the output of `conda info`? By chance, do you have any extra channels in your `.condarc` file?

**Comment by SultanOrazbayev** [comment]
Below is the content of `conda info`:

```python
     active environment : None
       user config file : ~/.condarc
 populated config files : ~/.condarc
          conda version : 4.12.0
    conda-build version : not installed
         python version : 3.8.5.final.0
       virtual packages : __osx=10.16=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : ~/miniconda  (writable)
      conda av data dir : ~/miniconda/etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : ~/miniconda/pkgs
                          ~/.conda/pkgs
       envs directories : ~/miniconda/envs
                          ~/.conda/envs
               platform : osx-64
             user-agent : conda/4.12.0 requests/2.27.1 CPython/3.8.5 Darwin/21.4.0 OSX/10.16
                UID:GID : <removed (not sure if needed)>
             netrc file : None
           offline mode : False
```

This is inside `~/.condarc` (don't recall changing these options manually, so might be the defaults):

```
always_yes: true
quiet: true
changeps1: false
```

Not sure if this applies to conda, but does it use some regional mirrors? If not, then perhaps there's some caching done by my ISP...
